trigger:
  - master

stages:
  - stage: build
    jobs:
      - job: build
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - checkout: self

          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: '10.x'

          - task: Gradle@2
            displayName: Gradle Build (also build the Docker image and the Angular-based SPA distribution)
            inputs:
              workingDirectory: ''
              gradleWrapperFile: 'gradlew'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.11'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/TEST-*.xml'
              sonarQubeRunAnalysis: true
              tasks: 'build'

#          - task: Docker@2
#            displayName: Login to the Azure Container Registry
#            inputs:
#              command: login
#              containerRegistry: dockerRegistryServiceConnection1
#
#          - task: Docker@2
#            displayName: Push the built image to the Azure Container Registry
#            inputs:
#              command: push
#              repository: someUser/contoso
#                tags: |
#                  tag1
#                  tag2
#
#          - task: Docker@2
#            displayName: Logout to the repository
#            inputs:
#              command: logout
#              containerRegistry: dockerRegistryServiceConnection1
