trigger:
  - master

stages:
  - stage: build
    jobs:
      - job: build
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - checkout: self

          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: '10.x'

          - task: Npm@1
            displayName: 'Execute npm install'
            inputs:
              command: 'install'
              workingDir: 'user-list-frontend'

          - task: Npm@1
            displayName: 'Install Angular CLI'
            inputs:
              command: 'custom'
              customCommand: 'install -g @angular/cli@'
              workingDir: 'user-list-frontend'

          - task: Gradle@2
            displayName: Gradle Build (also build the Docker image and the Angular-based SPA distribution)
            inputs:
              workingDirectory: ''
              gradleWrapperFile: 'gradlew'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.11'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/TEST-*.xml'
              tasks: 'build'

          - task: Docker@2
            displayName: Login to the Azure Container Registry
            inputs:
              command: login
              containerRegistry: acrShared001Connection

          - task: Docker@2
            displayName: Push the built image to the Azure Container Registry
            inputs:
              command: push
              repository: user-list-app
              tags: |
                latest
                1.0.0

          - task: Docker@2
            displayName: Logout to the repository
            inputs:
              command: logout
              containerRegistry: acrShared001Connection

          - task: PublishPipelineArtifact@1
            displayName: Publish the frontend app as artifact
            inputs:
              targetPath: 'user-list-frontend/build/distributions'
              artifactName: 'user-list-frontend'
