apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-list-deployment
  namespace: ns-user-list-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: user-list-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: user-list-app
    spec:
      containers:
        - name: user-list-app
          image: {{ imageName }}
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: 200m
              memory: 300M
            limits:
              cpu: 800m
              memory: 1.2G

