apiVersion: v1
kind: Service
metadata:
  name: user-list-app
  namespace: ns-user-list-dev
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: user-list-app
